export const GalleryItems = [
  {
    id: 'onboarding',
    short: 'Onboarding',
    description: 'GDSC Yonsei Onboarding',
    thumbnail: 'onboarding1.png',
    images: ['onboarding1.png', 'onboarding2.jpg', 'onboarding3.jpg', 'onboarding4.jpg'],
  },
  {
    id: 'jobfair',
    short: 'Job Fair',
    description: 'GDSC - Wanted Job Fair',
    thumbnail: 'JobFair1.jpeg',
    images: ['JobFair1.jpeg', 'JobFair2.jpg'],
  },
  {
    id: 'elice',
    short: 'Code Contest',
    description: 'GDSC - Elice Coding Contest.',
    thumbnail: 'Elice0.jpg',
    images: [
      'Elice0.jpg',
      'Elice1.jpg',
      'Elice2.jpg',
      'Elice3.jpg',
      'Elice4.jpg',
      'Elice5.jpg',
      'Elice6.jpg',
    ],
  },
  {
    id: 'devfest',
    short: 'DevFest',
    description: 'GDSC - GDG Songdo DevFest',
    thumbnail: 'DevFestSongdo1.jpg',
    images: ['DevFestSongdo1.jpg', 'DevFestSongdo2.jpg', 'DevFestSongdo3.jpg'],
  },
  {
    id: 'MT',
    short: 'MT',
    description: 'GDSC Yonsei MT',
    thumbnail: 'MT1.jpg',
    images: ['MT1.jpg', 'MT2.jpg', 'MT3.jpg'],
  },
  {
    id: 'cau',
    short: 'Yonsei - CAU',
    description: 'GDSC Yonsei & CAU Joint Tech Talks',
    thumbnail: 'CAU1.jpg',
    images: ['CAU1.jpg', 'CAU2.jpg'],
  },
  // {
  //   id: "caugist",
  //   short: "Yonsei - GIST - CAU",
  //   description: "GDSC Yonsei & GIST & CAU Joint Session",
  //   thumbnail: "CAUGIST.jpg",
  //   images: ["CAUGIST.jpg"],
  // },
];
